#pragma once

#include "usb/usb_descriptors.h"
#include "audio/format_values.h"

#define CFG_TUSB_MCU OPT_MCU_MIMXRT1XXX
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_HIGH_SPEED)
#define CFG_TUD_ENABLED 1
#define CFG_TUD_MAX_SPEED OPT_MODE_HIGH_SPEED
#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUSB_MEM_SECTION __attribute__((section(".dma")))
#define CFG_TUSB_MEM_ALIGN __attribute__((aligned(32)))
#define CFG_TUD_MEM_DCACHE_ENABLE 1
#define CFG_TUD_MEM_DCACHE_LINE_SIZE 32
#define CFG_TUD_AUDIO 1
#define CFG_TUD_CDC 0
#define CFG_TUD_MSC 0
#define CFG_TUD_HID 1
#define CFG_TUD_HID_EP_BUFSIZE 64
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 0
#define CFG_TUD_AUDIO_FUNC_1_DESC_LEN DYKODAC_AUDIO_DESC_LEN
#define CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE DYKODAC_RATE_48K
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX DYKODAC_CHANNELS
#define CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX DYKODAC_SUBSLOT_BYTES
#define CFG_TUD_AUDIO_FUNC_1_RESOLUTION_RX DYKODAC_VALID_BITS
#define CFG_TUD_AUDIO_ENABLE_EP_OUT 1
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX DYKODAC_USB_HS_MAX_PACKET
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ (8U * DYKODAC_USB_HS_MAX_PACKET)
#define CFG_TUD_AUDIO_ENABLE_FEEDBACK_EP 1
#define CFG_TUD_AUDIO_FUNC_1_N_AS_INT 1
#define CFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ 64
